Repository Williamm15/Assignment5, pull requests merged in 2021-12, with the labels that each got.

#5 Bug fixes and changes
  src/zombiewar/Child.java
  src/zombiewar/Soldier.java
  src/zombiewar/Tank.java
  src/zombiewar/Teacher.java
  src/zombiewar/ZombieWar.java
Labels: bug, documentation, enhancement

#6 Changed setter methods and build part of the characterAttack method
  src/zombiewar/Child.java
  src/zombiewar/CommonInfected.java
  src/zombiewar/Soldier.java
  src/zombiewar/Tank.java
  src/zombiewar/Teacher.java
  src/zombiewar/ZombieWar.java
Labels: bug, enhancement

#7 Completed character attack, sample run works, added methods, and bug …
  src/zombiewar/Child.java
  src/zombiewar/CommonInfected.java
  src/zombiewar/Soldier.java
  src/zombiewar/Tank.java
  src/zombiewar/Teacher.java
  src/zombiewar/ZombieWar.java
Labels: bug, documentation, enhancement

#8 Fixed grammar issues.
  src/zombiewar/ZombieWar.java
Labels: documentation

#9 Added output for character deaths by type.
  src/zombiewar/Child.java
  src/zombiewar/CommonInfected.java
  src/zombiewar/Soldier.java
  src/zombiewar/Tank.java
  src/zombiewar/Teacher.java
  src/zombiewar/ZombieWar.java
Labels: documentation, enhancement

#10 Added weapons to Zombie War
  src/zombiewar/Child.java
  src/zombiewar/CommonInfected.java
  src/zombiewar/Soldier.java
  src/zombiewar/Tank.java
  src/zombiewar/Teacher.java
  src/zombiewar/ZombieWar.java
Labels: bug, documentation, enhancement
